{% set name = "pytcs" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytcs-{{ version }}.tar.gz
  sha256: 6b8ac640c1fabdbaf2c84defe4c268cea0258824a547f41bbb5bfea221134f12

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=48
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - bidict
    - numpy
    - pandas >=1.4
    - xarray >=0.15
    - pint >=0.18
    - bottleneck >=1.3

test:
  imports:
    - pytcs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/CagtayFabry/pytcs/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python API for processing TwinCAT Scope data files
  description: |
    A Python package for reading exported TwinCAT Scope Files.
  doc_url: https://pytcs.readthedocs.io
  dev_url: https://github.com/CagtayFabry/pytcs/

extra:
  recipe-maintainers:
    - CagtayFabry
    - marscher
