{% set name = "pytcs" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytcs-{{ version }}.tar.gz
  sha256: 707472bf87e1b64a1e71ee8c95faf677288f5aa2d9ed7084ec5ce67b1f1164de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - bidict
    - numpy >=2
    - pandas >=2
    - polars >=1.21
    - xarray >=0.15
    - bottleneck >=1.3

test:
  imports:
    - pytcs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/CagtayFabry/pytcs/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python API for processing TwinCAT Scope data files
  description: |
    A Python package for reading exported TwinCAT Scope Files.
  doc_url: https://pytcs.readthedocs.io
  dev_url: https://github.com/CagtayFabry/pytcs/

extra:
  recipe-maintainers:
    - CagtayFabry
    - marscher
