{% set name = "pytcs" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytcs-{{ version }}.tar.gz
  sha256: 1e6bf0976c3144226b97bf568b4603614588ba4e7b69a8df814ea0c20a8e8050

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools >=48
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - bidict
    - numpy
    - pandas >=1.4
    - xarray >=0.15
    - pint >=0.18
    - bottleneck >=1.3

test:
  imports:
    - pytcs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CagtayFabry/pytcs/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python API for processing TwinCAT Scope data files
  description: |
    A Python package for reading exported TwinCAT Scope Files.
  doc_url: https://pytcs.readthedocs.io
  dev_url: https://github.com/CagtayFabry/pytcs/

extra:
  recipe-maintainers:
    - CagtayFabry
    - marscher
